[package]
name = "ziprs"
version = "1.0.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[dependencies]
zip = { path = "../zip", features = ["deflate-miniz"], default-features = false }
thiserror = "1.0.37"
jni_fn = "0.1.0"
jni = "0.19.0"
