name: Build

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - master

jobs:
  build:
    timeout-minutes: 8
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: "src"

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            $GITHUB_WORKSPACE/lib/rust/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('lib/rust/Cargo.lock') }}

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          default: true

      - name: Setup Rust Environment
        run: |
          rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android
          cargo ndk --version || cargo install cargo-ndk

      - name: Build and Maven publish
        id: build
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          mkdir -p $GITHUB_WORKSPACE/builds
          ./gradlew lib:build lib:publish --no-daemon
          mv -T lib/build/outputs/aar/lib-release.aar $GITHUB_WORKSPACE/builds/libziprs-release.aar
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d_%H-%M")"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.build.outputs.release_tag }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: builds/libziprs-release.aar
